# Generated by Django 3.1.4 on 2020-12-17 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postdislike',
            name='created',
        ),
        migrations.RemoveField(
            model_name='postlike',
            name='created',
        ),
    ]
