# Generated by Django 3.1.4 on 2020-12-17 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_remove_post_likes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostLikeDislike',
        ),
    ]
